In [1]:
import pandas as pd
dataset=pd.read_csv('marks.csv')

In [2]:
dataset

name  hrs  marks
0    Raj    3     30
1  Aryan    6     60
2  Nakul    8     80
3   Ravi    5     50

In [3]:
x=dataset["hrs"].values

In [4]:
x=x.reshape(-1,1)

In [5]:
x

array([[3],
       [6],
       [8],
       [5]], dtype=int64)

In [6]:
y=dataset["marks"].values

In [7]:
y=y.reshape(-1,1)

In [8]:
y

array([[30],
       [60],
       [80],
       [50]], dtype=int64)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
mind=LinearRegression()

In [11]:
mind.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
mind.predict([[7]])

array([[70.]])

In [13]:
mind.coef_

array([[10.]])

In [14]:
import joblib

In [15]:
joblib.dump(mind,'marks.pk1')

['marks.pk1']